// MonolithUIAccessibilityActions.cpp
#include "MonolithUIAccessibilityActions.h"
#include "MonolithParamSchema.h"
#include "Dom/JsonObject.h"
#include "Dom/JsonValue.h"
#include "Misc/FileHelper.h"
#include "Misc/Paths.h"
#include "WidgetBlueprint.h"
#include "Blueprint/WidgetTree.h"
#include "Components/Widget.h"
#include "Components/PanelWidget.h"
#include "Components/TextBlock.h"
#include "Components/RichTextBlock.h"
#include "Components/Button.h"
#include "Components/CheckBox.h"
#include "Components/Slider.h"
#include "Components/EditableTextBox.h"
#include "Components/ComboBoxString.h"
#include "Components/InputKeySelector.h"
#include "Framework/Application/SlateApplication.h"
#include "Rendering/SlateRenderer.h"

// ============================================================================
// Registration
// ============================================================================

void FMonolithUIAccessibilityActions::RegisterActions(FMonolithToolRegistry& Registry)
{
    Registry.RegisterAction(
        TEXT("ui"), TEXT("scaffold_accessibility_subsystem"),
        TEXT("Generate a UGameInstanceSubsystem for accessibility settings with reduced motion, colorblind, font scale, and toggle options"),
        FMonolithActionHandler::CreateStatic(&HandleScaffoldAccessibilitySubsystem),
        FParamSchemaBuilder()
            .Required(TEXT("class_name"), TEXT("string"), TEXT("Subsystem class name, e.g. UAccessibilitySubsystem"))
            .Required(TEXT("module_name"), TEXT("string"), TEXT("Target module name"))
            .Build()
    );

    Registry.RegisterAction(
        TEXT("ui"), TEXT("audit_accessibility"),
        TEXT("Audit a Widget Blueprint for accessibility issues: small fonts, missing focus, navigation, tooltips"),
        FMonolithActionHandler::CreateStatic(&HandleAuditAccessibility),
        FParamSchemaBuilder()
            .Required(TEXT("asset_path"), TEXT("string"), TEXT("Widget Blueprint asset path"))
            .Build()
    );

    Registry.RegisterAction(
        TEXT("ui"), TEXT("set_colorblind_mode"),
        TEXT("Set the colorblind correction mode at runtime"),
        FMonolithActionHandler::CreateStatic(&HandleSetColorblindMode),
        FParamSchemaBuilder()
            .Required(TEXT("mode"), TEXT("string"), TEXT("Mode: Normal, Deuteranope, Protanope, Tritanope"))
            .Optional(TEXT("severity"), TEXT("integer"), TEXT("Severity 0-10 (default: 5)"), TEXT("5"))
            .Optional(TEXT("correct"), TEXT("boolean"), TEXT("Apply correction filter (default: true)"), TEXT("true"))
            .Build()
    );

    Registry.RegisterAction(
        TEXT("ui"), TEXT("set_text_scale"),
        TEXT("Set the global UI text/application scale at runtime"),
        FMonolithActionHandler::CreateStatic(&HandleSetTextScale),
        FParamSchemaBuilder()
            .Required(TEXT("scale"), TEXT("number"), TEXT("Scale factor 0.75-1.5"))
            .Build()
    );
}

// ============================================================================
// scaffold_accessibility_subsystem
// ============================================================================

FMonolithActionResult FMonolithUIAccessibilityActions::HandleScaffoldAccessibilitySubsystem(const TSharedPtr<FJsonObject>& Params)
{
    FString ClassName = Params->GetStringField(TEXT("class_name"));
    FString ModuleName = Params->GetStringField(TEXT("module_name"));
    if (ClassName.IsEmpty() || ModuleName.IsEmpty())
    {
        return FMonolithActionResult::Error(TEXT("Missing required params: class_name, module_name"));
    }

    FString CleanName = ClassName;
    if (CleanName.StartsWith(TEXT("U"))) CleanName = CleanName.RightChop(1);

    FString ApiMacro = ModuleName.ToUpper() + TEXT("_API");

    // Resolve source dir
    FString ProjectDir = FPaths::ProjectDir();
    FString SourceDir = FPaths::Combine(ProjectDir, TEXT("Source"), ModuleName);
    if (!FPaths::DirectoryExists(SourceDir))
    {
        return FMonolithActionResult::Error(
            FString::Printf(TEXT("Source directory not found: %s"), *SourceDir));
    }

    // Check for existing file
    FString HeaderPath = FPaths::Combine(SourceDir, CleanName + TEXT(".h"));
    FString CppPath = FPaths::Combine(SourceDir, CleanName + TEXT(".cpp"));
    if (FPaths::FileExists(HeaderPath))
    {
        return FMonolithActionResult::Error(
            FString::Printf(TEXT("File already exists: %s — delete or rename before scaffolding"), *HeaderPath));
    }

    // ---- Header ----
    FString Header;
    Header += TEXT("// Auto-generated by Monolith scaffold_accessibility_subsystem\n");
    Header += TEXT("#pragma once\n\n");
    Header += TEXT("#include \"CoreMinimal.h\"\n");
    Header += TEXT("#include \"Subsystems/GameInstanceSubsystem.h\"\n");
    Header += FString::Printf(TEXT("#include \"%s.generated.h\"\n\n"), *CleanName);

    Header += TEXT("UENUM(BlueprintType)\n");
    Header += TEXT("enum class EAccessibilityColorblindMode : uint8\n");
    Header += TEXT("{\n");
    Header += TEXT("\tNormal,\n");
    Header += TEXT("\tDeuteranope,\n");
    Header += TEXT("\tProtanope,\n");
    Header += TEXT("\tTritanope\n");
    Header += TEXT("};\n\n");

    Header += TEXT("UENUM(BlueprintType)\n");
    Header += TEXT("enum class EHoldVsToggle : uint8\n");
    Header += TEXT("{\n");
    Header += TEXT("\tHold,\n");
    Header += TEXT("\tToggle\n");
    Header += TEXT("};\n\n");

    Header += FString::Printf(TEXT("UCLASS()\nclass %s %s : public UGameInstanceSubsystem\n{\n\tGENERATED_BODY()\n\npublic:\n"), *ApiMacro, *ClassName);

    Header += TEXT("\tvirtual void Initialize(FSubsystemCollectionBase& Collection) override;\n\n");

    Header += TEXT("\t/** Apply all current accessibility settings to engine systems */\n");
    Header += TEXT("\tUFUNCTION(BlueprintCallable, Category = \"Accessibility\")\n");
    Header += TEXT("\tvoid ApplySettings();\n\n");

    // Visual
    Header += TEXT("\t// --- Visual ---\n");
    Header += TEXT("\tUPROPERTY(EditAnywhere, BlueprintReadWrite, Category = \"Accessibility|Visual\")\n");
    Header += TEXT("\tbool bReducedMotion = false;\n\n");
    Header += TEXT("\tUPROPERTY(EditAnywhere, BlueprintReadWrite, Category = \"Accessibility|Visual\")\n");
    Header += TEXT("\tbool bHighContrast = false;\n\n");
    Header += TEXT("\tUPROPERTY(EditAnywhere, BlueprintReadWrite, Category = \"Accessibility|Visual\", meta = (ClampMin = \"0.75\", ClampMax = \"1.5\"))\n");
    Header += TEXT("\tfloat FontScale = 1.0f;\n\n");
    Header += TEXT("\tUPROPERTY(EditAnywhere, BlueprintReadWrite, Category = \"Accessibility|Visual\")\n");
    Header += TEXT("\tEAccessibilityColorblindMode ColorblindMode = EAccessibilityColorblindMode::Normal;\n\n");
    Header += TEXT("\tUPROPERTY(EditAnywhere, BlueprintReadWrite, Category = \"Accessibility|Visual\", meta = (ClampMin = \"0\", ClampMax = \"10\"))\n");
    Header += TEXT("\tint32 ColorblindSeverity = 5;\n\n");

    // Subtitles
    Header += TEXT("\t// --- Subtitles ---\n");
    Header += TEXT("\tUPROPERTY(EditAnywhere, BlueprintReadWrite, Category = \"Accessibility|Subtitles\")\n");
    Header += TEXT("\tbool bSubtitlesEnabled = true;\n\n");
    Header += TEXT("\tUPROPERTY(EditAnywhere, BlueprintReadWrite, Category = \"Accessibility|Subtitles\", meta = (ClampMin = \"14\", ClampMax = \"36\"))\n");
    Header += TEXT("\tint32 SubtitleFontSize = 20;\n\n");

    // Input
    Header += TEXT("\t// --- Input Accessibility ---\n");
    Header += TEXT("\tUPROPERTY(EditAnywhere, BlueprintReadWrite, Category = \"Accessibility|Input\")\n");
    Header += TEXT("\tbool bToggleSprint = false;\n\n");
    Header += TEXT("\tUPROPERTY(EditAnywhere, BlueprintReadWrite, Category = \"Accessibility|Input\")\n");
    Header += TEXT("\tbool bToggleCrouch = false;\n\n");
    Header += TEXT("\tUPROPERTY(EditAnywhere, BlueprintReadWrite, Category = \"Accessibility|Input\")\n");
    Header += TEXT("\tbool bToggleAim = false;\n\n");
    Header += TEXT("\tUPROPERTY(EditAnywhere, BlueprintReadWrite, Category = \"Accessibility|Input\")\n");
    Header += TEXT("\tEHoldVsToggle HoldVsToggle = EHoldVsToggle::Hold;\n\n");
    Header += TEXT("\tUPROPERTY(EditAnywhere, BlueprintReadWrite, Category = \"Accessibility|Input\", meta = (ClampMin = \"0.0\", ClampMax = \"1.0\"))\n");
    Header += TEXT("\tfloat TremorTolerance = 0.0f;\n\n");

    Header += TEXT("};\n");

    // ---- Cpp ----
    FString Cpp;
    Cpp += TEXT("// Auto-generated by Monolith scaffold_accessibility_subsystem\n");
    Cpp += FString::Printf(TEXT("#include \"%s.h\"\n"), *CleanName);
    Cpp += TEXT("#include \"Framework/Application/SlateApplication.h\"\n");
    Cpp += TEXT("#include \"Rendering/SlateRenderer.h\"\n\n");

    // Initialize
    Cpp += FString::Printf(TEXT("void %s::Initialize(FSubsystemCollectionBase& Collection)\n{\n"), *ClassName);
    Cpp += TEXT("\tSuper::Initialize(Collection);\n");
    Cpp += TEXT("\tUE_LOG(LogTemp, Log, TEXT(\"Accessibility subsystem initialized\"));\n");
    Cpp += TEXT("}\n\n");

    // ApplySettings
    Cpp += FString::Printf(TEXT("void %s::ApplySettings()\n{\n"), *ClassName);

    // Colorblind
    Cpp += TEXT("\t// Colorblind correction\n");
    Cpp += TEXT("\tEColorVisionDeficiency CVD = EColorVisionDeficiency::NormalVision;\n");
    Cpp += TEXT("\tswitch (ColorblindMode)\n");
    Cpp += TEXT("\t{\n");
    Cpp += TEXT("\tcase EAccessibilityColorblindMode::Deuteranope: CVD = EColorVisionDeficiency::Deuteranope; break;\n");
    Cpp += TEXT("\tcase EAccessibilityColorblindMode::Protanope:   CVD = EColorVisionDeficiency::Protanope;   break;\n");
    Cpp += TEXT("\tcase EAccessibilityColorblindMode::Tritanope:   CVD = EColorVisionDeficiency::Tritanope;   break;\n");
    Cpp += TEXT("\tdefault: break;\n");
    Cpp += TEXT("\t}\n");
    Cpp += TEXT("\tFSlateApplication::Get().GetRenderer()->SetColorVisionDeficiencyType(CVD, ColorblindSeverity, true, false);\n\n");

    // Font/UI scale
    Cpp += TEXT("\t// UI scale (affects font readability)\n");
    Cpp += TEXT("\tFSlateApplication::Get().SetApplicationScale(FontScale);\n\n");

    // Subtitles
    Cpp += TEXT("\t// Subtitles\n");
    Cpp += TEXT("\tif (GEngine)\n");
    Cpp += TEXT("\t{\n");
    Cpp += TEXT("\t\tGEngine->bSubtitlesEnabled = bSubtitlesEnabled;\n");
    Cpp += TEXT("\t}\n\n");

    Cpp += TEXT("\tUE_LOG(LogTemp, Log, TEXT(\"Accessibility settings applied: ColorblindMode=%d, FontScale=%.2f, Subtitles=%s\"),\n");
    Cpp += TEXT("\t\t(int32)ColorblindMode, FontScale, bSubtitlesEnabled ? TEXT(\"On\") : TEXT(\"Off\"));\n");
    Cpp += TEXT("}\n");

    // Write files
    if (!FFileHelper::SaveStringToFile(Header, *HeaderPath, FFileHelper::EEncodingOptions::ForceUTF8WithoutBOM))
    {
        return FMonolithActionResult::Error(FString::Printf(TEXT("Failed to write header: %s"), *HeaderPath));
    }
    if (!FFileHelper::SaveStringToFile(Cpp, *CppPath, FFileHelper::EEncodingOptions::ForceUTF8WithoutBOM))
    {
        return FMonolithActionResult::Error(FString::Printf(TEXT("Failed to write cpp: %s"), *CppPath));
    }

    TSharedPtr<FJsonObject> Result = MakeShared<FJsonObject>();
    Result->SetStringField(TEXT("header_path"), HeaderPath);
    Result->SetStringField(TEXT("cpp_path"), CppPath);
    Result->SetStringField(TEXT("class_name"), ClassName);

    TArray<TSharedPtr<FJsonValue>> Flags;
    Flags.Add(MakeShared<FJsonValueString>(TEXT("bReducedMotion")));
    Flags.Add(MakeShared<FJsonValueString>(TEXT("bHighContrast")));
    Flags.Add(MakeShared<FJsonValueString>(TEXT("FontScale")));
    Flags.Add(MakeShared<FJsonValueString>(TEXT("ColorblindMode")));
    Flags.Add(MakeShared<FJsonValueString>(TEXT("bSubtitlesEnabled")));
    Flags.Add(MakeShared<FJsonValueString>(TEXT("SubtitleFontSize")));
    Flags.Add(MakeShared<FJsonValueString>(TEXT("bToggleSprint")));
    Flags.Add(MakeShared<FJsonValueString>(TEXT("bToggleCrouch")));
    Flags.Add(MakeShared<FJsonValueString>(TEXT("bToggleAim")));
    Flags.Add(MakeShared<FJsonValueString>(TEXT("HoldVsToggle")));
    Flags.Add(MakeShared<FJsonValueString>(TEXT("TremorTolerance")));
    Result->SetArrayField(TEXT("accessibility_flags"), Flags);

    return FMonolithActionResult::Success(Result);
}

// ============================================================================
// audit_accessibility
// ============================================================================

FMonolithActionResult FMonolithUIAccessibilityActions::HandleAuditAccessibility(const TSharedPtr<FJsonObject>& Params)
{
    FString AssetPath = Params->GetStringField(TEXT("asset_path"));
    if (AssetPath.IsEmpty())
    {
        return FMonolithActionResult::Error(TEXT("Missing required param: asset_path"));
    }

    // Load widget blueprint
    UObject* Loaded = StaticLoadObject(UWidgetBlueprint::StaticClass(), nullptr, *AssetPath);
    if (!Loaded)
    {
        FString CleanPath = AssetPath;
        if (!CleanPath.StartsWith(TEXT("/")))
        {
            CleanPath = TEXT("/Game/") + CleanPath;
        }
        Loaded = StaticLoadObject(UWidgetBlueprint::StaticClass(), nullptr, *CleanPath);
    }
    UWidgetBlueprint* WBP = Cast<UWidgetBlueprint>(Loaded);
    if (!WBP)
    {
        return FMonolithActionResult::Error(
            FString::Printf(TEXT("Widget Blueprint not found: %s"), *AssetPath));
    }

    if (!WBP->WidgetTree)
    {
        return FMonolithActionResult::Error(TEXT("WidgetTree is null"));
    }

    TArray<TSharedPtr<FJsonValue>> Issues;

    // Collect all widgets
    TArray<UWidget*> AllWidgets;
    WBP->WidgetTree->GetAllWidgets(AllWidgets);

    for (UWidget* Widget : AllWidgets)
    {
        if (!Widget) continue;
        FString WidgetName = Widget->GetName();

        // --- Check 1: Font size on TextBlock ---
        if (UTextBlock* TextBlock = Cast<UTextBlock>(Widget))
        {
            const FSlateFontInfo& FontInfo = TextBlock->GetFont();
            if (FontInfo.Size < 18)
            {
                TSharedPtr<FJsonObject> Issue = MakeShared<FJsonObject>();
                Issue->SetStringField(TEXT("widget_name"), WidgetName);
                Issue->SetStringField(TEXT("issue"),
                    FString::Printf(TEXT("Font size %.0f is below recommended minimum of 18pt for accessibility"), FontInfo.Size));
                Issue->SetStringField(TEXT("severity"), TEXT("warning"));
                Issue->SetStringField(TEXT("recommendation"), TEXT("Increase font size to at least 18pt, or ensure FontScale accessibility setting is applied"));
                Issues.Add(MakeShared<FJsonValueObject>(Issue));
            }
        }

        // --- Check 2: Font size on RichTextBlock ---
        if (URichTextBlock* RichText = Cast<URichTextBlock>(Widget))
        {
            const FSlateFontInfo& FontInfo = RichText->GetDefaultTextStyle().Font;
            if (FontInfo.Size < 18)
            {
                TSharedPtr<FJsonObject> Issue = MakeShared<FJsonObject>();
                Issue->SetStringField(TEXT("widget_name"), WidgetName);
                Issue->SetStringField(TEXT("issue"),
                    FString::Printf(TEXT("Default font size %.0f is below recommended minimum of 18pt"), FontInfo.Size));
                Issue->SetStringField(TEXT("severity"), TEXT("warning"));
                Issue->SetStringField(TEXT("recommendation"), TEXT("Increase default text style font size to at least 18pt"));
                Issues.Add(MakeShared<FJsonValueObject>(Issue));
            }
        }

        // --- Check 3: Button missing tooltip ---
        if (UButton* Button = Cast<UButton>(Widget))
        {
            FText Tooltip = Button->GetToolTipText();
            if (Tooltip.IsEmpty())
            {
                TSharedPtr<FJsonObject> Issue = MakeShared<FJsonObject>();
                Issue->SetStringField(TEXT("widget_name"), WidgetName);
                Issue->SetStringField(TEXT("issue"), TEXT("Button has no tooltip — screen readers and hover descriptions won't work"));
                Issue->SetStringField(TEXT("severity"), TEXT("warning"));
                Issue->SetStringField(TEXT("recommendation"), TEXT("Set ToolTipText to describe the button's action"));
                Issues.Add(MakeShared<FJsonValueObject>(Issue));
            }

            // Check if Normal and Hovered styles are identical — indicates no visual feedback for focus/hover
            // Note: FButtonStyle has Normal/Hovered/Pressed/Disabled — no Focused member exists
            if (Button->GetStyle().Normal == Button->GetStyle().Hovered)
            {
                TSharedPtr<FJsonObject> Issue = MakeShared<FJsonObject>();
                Issue->SetStringField(TEXT("widget_name"), WidgetName);
                Issue->SetStringField(TEXT("issue"), TEXT("Button Normal and Hovered styles are identical — no visible hover/focus indicator"));
                Issue->SetStringField(TEXT("severity"), TEXT("error"));
                Issue->SetStringField(TEXT("recommendation"), TEXT("Set a distinct Hovered style (e.g. border color or tint) so keyboard/gamepad users can see which button is selected"));
                Issues.Add(MakeShared<FJsonValueObject>(Issue));
            }
        }

        // --- Check 4: Interactive widgets missing tooltip ---
        if (Cast<UCheckBox>(Widget) || Cast<USlider>(Widget) || Cast<UComboBoxString>(Widget) || Cast<UInputKeySelector>(Widget))
        {
            FText Tooltip = Widget->GetToolTipText();
            if (Tooltip.IsEmpty())
            {
                TSharedPtr<FJsonObject> Issue = MakeShared<FJsonObject>();
                Issue->SetStringField(TEXT("widget_name"), WidgetName);
                Issue->SetStringField(TEXT("issue"), TEXT("Interactive widget has no tooltip"));
                Issue->SetStringField(TEXT("severity"), TEXT("warning"));
                Issue->SetStringField(TEXT("recommendation"), TEXT("Set ToolTipText to describe the widget's purpose"));
                Issues.Add(MakeShared<FJsonValueObject>(Issue));
            }
        }

        // --- Check 5: Navigation rules ---
        if (Widget->GetIsEnabled())
        {
            // Check if widget is focusable but has no explicit navigation rules
            bool bIsFocusable = false;
            if (UButton* Btn = Cast<UButton>(Widget)) bIsFocusable = Btn->GetIsFocusable();
            else if (UCheckBox* CB = Cast<UCheckBox>(Widget)) bIsFocusable = CB->GetIsFocusable();
            else if (Cast<USlider>(Widget)) bIsFocusable = true;
            else if (Cast<UEditableTextBox>(Widget)) bIsFocusable = true;
            else if (Cast<UComboBoxString>(Widget)) bIsFocusable = true;

            if (bIsFocusable)
            {
                // Navigation data lives on UWidgetNavigation (not UWidget directly)
                bool bHasExplicitNav = false;
                if (Widget->Navigation)
                {
                    const FWidgetNavigationData& NavUp = Widget->Navigation->GetNavigationData(EUINavigation::Up);
                    const FWidgetNavigationData& NavDown = Widget->Navigation->GetNavigationData(EUINavigation::Down);
                    const FWidgetNavigationData& NavLeft = Widget->Navigation->GetNavigationData(EUINavigation::Left);
                    const FWidgetNavigationData& NavRight = Widget->Navigation->GetNavigationData(EUINavigation::Right);

                    bHasExplicitNav = (NavUp.Rule != EUINavigationRule::Escape) ||
                                     (NavDown.Rule != EUINavigationRule::Escape) ||
                                     (NavLeft.Rule != EUINavigationRule::Escape) ||
                                     (NavRight.Rule != EUINavigationRule::Escape);
                }

                if (!bHasExplicitNav)
                {
                    TSharedPtr<FJsonObject> Issue = MakeShared<FJsonObject>();
                    Issue->SetStringField(TEXT("widget_name"), WidgetName);
                    Issue->SetStringField(TEXT("issue"), TEXT("Focusable widget has no explicit navigation rules — gamepad/keyboard navigation may be unpredictable"));
                    Issue->SetStringField(TEXT("severity"), TEXT("warning"));
                    Issue->SetStringField(TEXT("recommendation"), TEXT("Set Up/Down/Left/Right navigation rules to Explicit or Wrap for predictable focus traversal"));
                    Issues.Add(MakeShared<FJsonValueObject>(Issue));
                }
            }
        }
    }

    TSharedPtr<FJsonObject> Result = MakeShared<FJsonObject>();
    Result->SetStringField(TEXT("asset_path"), AssetPath);
    Result->SetNumberField(TEXT("widget_count"), AllWidgets.Num());
    Result->SetNumberField(TEXT("issue_count"), Issues.Num());
    Result->SetArrayField(TEXT("issues"), Issues);

    int32 Errors = 0, Warnings = 0;
    for (const auto& I : Issues)
    {
        FString Sev = I->AsObject()->GetStringField(TEXT("severity"));
        if (Sev == TEXT("error")) Errors++;
        else Warnings++;
    }
    Result->SetNumberField(TEXT("error_count"), Errors);
    Result->SetNumberField(TEXT("warning_count"), Warnings);

    if (Issues.Num() == 0)
    {
        Result->SetStringField(TEXT("summary"), TEXT("No accessibility issues found — nice work!"));
    }
    else
    {
        Result->SetStringField(TEXT("summary"),
            FString::Printf(TEXT("%d issues found: %d errors, %d warnings"), Issues.Num(), Errors, Warnings));
    }

    return FMonolithActionResult::Success(Result);
}

// ============================================================================
// set_colorblind_mode (RUNTIME)
// ============================================================================

FMonolithActionResult FMonolithUIAccessibilityActions::HandleSetColorblindMode(const TSharedPtr<FJsonObject>& Params)
{
    FString Mode = Params->GetStringField(TEXT("mode"));
    if (Mode.IsEmpty())
    {
        return FMonolithActionResult::Error(TEXT("Missing required param: mode"));
    }

    int32 Severity = 5;
    if (Params->HasField(TEXT("severity")))
    {
        Severity = FMath::Clamp((int32)Params->GetNumberField(TEXT("severity")), 0, 10);
    }

    bool bCorrect = true;
    if (Params->HasField(TEXT("correct")))
    {
        bCorrect = Params->GetBoolField(TEXT("correct"));
    }

    EColorVisionDeficiency CVD = EColorVisionDeficiency::NormalVision;
    if (Mode == TEXT("Deuteranope"))      CVD = EColorVisionDeficiency::Deuteranope;
    else if (Mode == TEXT("Protanope"))   CVD = EColorVisionDeficiency::Protanope;
    else if (Mode == TEXT("Tritanope"))   CVD = EColorVisionDeficiency::Tritanope;
    else if (Mode != TEXT("Normal"))
    {
        return FMonolithActionResult::Error(
            FString::Printf(TEXT("Unknown mode: %s — use Normal, Deuteranope, Protanope, or Tritanope"), *Mode));
    }

    FSlateApplication::Get().GetRenderer()->SetColorVisionDeficiencyType(
        CVD, Severity, bCorrect, false);

    TSharedPtr<FJsonObject> Result = MakeShared<FJsonObject>();
    Result->SetStringField(TEXT("mode"), Mode);
    Result->SetNumberField(TEXT("severity"), Severity);
    Result->SetBoolField(TEXT("correct"), bCorrect);
    Result->SetBoolField(TEXT("applied"), true);
    return FMonolithActionResult::Success(Result);
}

// ============================================================================
// set_text_scale (RUNTIME)
// ============================================================================

FMonolithActionResult FMonolithUIAccessibilityActions::HandleSetTextScale(const TSharedPtr<FJsonObject>& Params)
{
    if (!Params->HasField(TEXT("scale")))
    {
        return FMonolithActionResult::Error(TEXT("Missing required param: scale"));
    }

    float Scale = (float)Params->GetNumberField(TEXT("scale"));
    Scale = FMath::Clamp(Scale, 0.75f, 1.5f);

    FSlateApplication::Get().SetApplicationScale(Scale);

    TSharedPtr<FJsonObject> Result = MakeShared<FJsonObject>();
    Result->SetNumberField(TEXT("scale"), Scale);
    Result->SetBoolField(TEXT("applied"), true);
    return FMonolithActionResult::Success(Result);
}
